services:
  # rest api
  fastapi:
    build:
      context: ./rest_api
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    volumes:
      - ./rest_api:/app
    ports:
      - 8082:8082
    env_file:
      - .credentials
    depends_on:
      - postgres-db
      - mongo-db

  # postgres database with UI
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .credentials
    environment:
      TZ: UTC
      PGTZ: UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-postgres
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-db

  # mongo database with UI
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .credentials
    volumes:
      - mongo-db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .credentials

volumes:
  postgres-db:
  mongo-db:


