services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .credentials
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-db:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer-postgres
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-db:
  redis-db:


