# Generated by Django 5.1.5 on 2025-01-30 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scraped_id', models.IntegerField(unique=True)),
                ('scraped_link', models.URLField(unique=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='BootsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('collections', models.CharField(blank=True, max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_type', models.CharField(blank=True, max_length=100, null=True)),
                ('class_type', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_binding', models.CharField(blank=True, max_length=100, null=True)),
                ('boots_with_sock', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('plays_in_these_boots', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturers_data', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boots_features', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='BallsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('ball_size', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_type', models.CharField(blank=True, max_length=100, null=True)),
                ('class_type', models.CharField(blank=True, max_length=100, null=True)),
                ('collection', models.CharField(blank=True, max_length=100, null=True)),
                ('connecting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturers_data', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_features', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.CharField(max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ecommerce.product')),
            ],
        ),
    ]
