# Generated by Django 5.1.5 on 2025-01-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BallsFeatures',
            new_name='Balls_Features',
        ),
        migrations.RenameModel(
            old_name='BootsFeatures',
            new_name='Boots_Features',
        ),
    ]
