# Generated by Django 5.1.5 on 2025-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
