# Generated by Django 5.1.5 on 2025-01-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_ballsfeatures_balls_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balls_features',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='balls_features', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.categories'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ecommerce.product'),
        ),
        migrations.CreateModel(
            name='BootsFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('collections', models.CharField(blank=True, max_length=100, null=True)),
                ('age_group', models.CharField(blank=True, max_length=100, null=True)),
                ('ground_type', models.CharField(blank=True, max_length=100, null=True)),
                ('class_type', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_binding', models.CharField(blank=True, max_length=100, null=True)),
                ('boots_with_sock', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('plays_in_these_boots', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturers_data', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='boots_features', to='ecommerce.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Boots_Features',
        ),
    ]
