# Generated by Django 5.1.5 on 2025-01-31 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_category_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BootsFeatures',
            new_name='Boots_Features',
        ),
    ]
