# Generated by Django 5.1.5 on 2025-01-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_categories_created_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='scraped_id',
            new_name='scraped_num',
        ),
    ]
