# Generated by Django 5.1.5 on 2025-02-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_product_discount_product_before_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
