# Generated by Django 5.1.5 on 2025-02-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_alter_product_before_discount_alter_product_img_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='label_name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='before_discount',
            new_name='price_before_discount',
        ),
        migrations.RenameField(
            model_name='product_images',
            old_name='image_name',
            new_name='img_path',
        ),
        migrations.RenameField(
            model_name='sizes',
            old_name='size_num',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_pct',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
