# Generated by Django 5.1.5 on 2025-02-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_rename_label_name_labels_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scraped_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='scraped_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
