# Generated by Django 5.1.5 on 2025-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_product_scraped_link_alter_product_scraped_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
